---
title: "Spatial Spike Neural Networks"
author: "Luca Simonetti"
date: "2025-01-30"
categories: [programming, web development, research, diary, R&D]
---

# Ricerca e Sviluppo

Voglio provare a studiare un tipo di rete neurale di cui non ho trovato citazioni in ambito di ricerca. 
Di base Una rete neurale spiking (SNN) è un tipo di Neural Network che si avvicina maggiormente al funzionamento dei neuroni biologici. A differenza delle reti neurali tradizionali che trasmettono valori continui (ovvero fanno le moltiplicazioni direttamente), le SNN elaborano le informazioni attraverso "spike", ovvero eventi discreti nel tempo, rendendole computazionalmente più efficienti. Queste reti codificano le informazioni nella temporizzazione e nella frequenza degli spike, consentendo loro di catturare dinamiche temporali complesse e potenzialmente imitare la capacità di apprendimento del cervello.

L'elemento che voglio introdurre è quello di strutture (basate su grafi) che includano all'interno della rete anche il concetto di *vicinanza* dei neuroni della rete.
Voglio inoltre provare a comprendere se i neuroni possono spostarsi all'interno della struttura a grafo.

In altre parole: do una struttura alla rete, come ad esempio delle strutture simili a quelle cristalline, e posiziono i neuroni.
Man mano che apprendono pattern all'interno dei dati, li faccio *muovere* seguendo la struttura data, seguendo l'apprendimento Hebbiano

