project:
  type: website

website:
  title: "L."
  site-url: https://theghoul21.github.io/
  open-graph: 
    title: "L."
    description: "Personal website of Luca Simonetti - Research Projects, Blog Posts, and sh*t like that."
    site-name: "L."  
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Blog
        menu:
          - text: "Blog Posts"
            href: blog/index.qmd
          - text: "Categories"
            href: blog/categories.qmd
      - text: Projects
        menu:
          - text: "Research Projects"
            href: projects/index.qmd
    
  page-footer: 
    center: "Copyright 2025, Luca Simonetti"
    background: light

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true