project:
  type: website

website:
  title: "L."
  site-url: https://theghoul21.github.io/
  open-graph: 
    title: "L."
    description: "Personal website of Luca Simonetti - Research Projects, Blog Posts, and sh*t like that."
    site-name: "L."
    image: "/images/278270564_10159906873598664_2201636379743763738_n.jpg"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: blog/index.qmd
        text: Blog
      - href: projects/index.qmd
        text: Projects
      - text: Lecture notes
        menu:
          - text: "Complexity and Information Theory"
            href: https://theghoul21.github.io/CIT-2024-2025/
            target: _blank
          - text: "Deep Learning"
            href: https://theghoul21.github.io/DL-2024-2025/
            target: _blank
          - text: "Ricerca Operativa"
            href: https://theghoul21.github.io/RO-2024-2025/
            target: _blank
          - text: "Foundations of Neural Networks"
            href: https://theghoul21.github.io/FNN-2024-2025/
            target: _blank

    
  page-footer: 
    center: "Copyright 2025, Luca Simonetti"
    background: light

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

page-layout: full
title-block-banner: true
